//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication.Framework.Message {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrameworkDebugMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkDebugMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication.Framework.Message.FrameworkDebugMessage", typeof(FrameworkDebugMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Exist empty file path in Batch Backup Folder List : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BatchBackupFolderList_EmptyFolder {
            get {
                return ResourceManager.GetString("BatchBackupFolderList_EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View found in cache : {0} Method, viewName {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CacheFoundTargetView {
            get {
                return ResourceManager.GetString("CacheFoundTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ext Command info: exec file {0}, argument {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandExecuteUtilityExecuteMessage {
            get {
                return ResourceManager.GetString("CommandExecuteUtilityExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command execute : command name {0}, args {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandStartMessage {
            get {
                return ResourceManager.GetString("CommandStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View instance create : {0} Method, viewName {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateInstanceTargetView {
            get {
                return ResourceManager.GetString("CreateInstanceTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionBalloonTitle {
            get {
                return ResourceManager.GetString("ExceptionBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exist same process : Process Id = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExistSameProcess {
            get {
                return ResourceManager.GetString("ExistSameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not found or not implements IService : Target type {0}, Service attr type {1}, Service name = {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InjectionServiceIsNullOrNotImplements {
            get {
                return ResourceManager.GetString("InjectionServiceIsNullOrNotImplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found Service : Target object {0}, Field info {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InjectServiceNotFoundServiceMessage {
            get {
                return ResourceManager.GetString("InjectServiceNotFoundServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model file not found : type {0}, method {1}, filepath {2}, serialize type {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelSerialize_FileNotFound {
            get {
                return ResourceManager.GetString("ModelSerialize_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model serialize type unsupported : type {0}, method {1}, serialize type {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelSerialize_UnsupportedSerializeType {
            get {
                return ResourceManager.GetString("ModelSerialize_UnsupportedSerializeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not found service : Target type {0}, Service attr type {1}, Service name = {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundInjectionService {
            get {
                return ResourceManager.GetString("NotFoundInjectionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found Mapped Type : TypeName = {0}, SrcType = {1}, Dest Type = {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundMappedType {
            get {
                return ResourceManager.GetString("NotFoundMappedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View not found : {0} Method, viewName {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundTargetView {
            get {
                return ResourceManager.GetString("NotFoundTargetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Process : Process Id = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProessEndMessage {
            get {
                return ResourceManager.GetString("ProessEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command line info : Argument = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProessStartCommandLineMessage {
            get {
                return ResourceManager.GetString("ProessStartCommandLineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Process : Process Id = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProessStartMessage {
            get {
                return ResourceManager.GetString("ProessStartMessage", resourceCulture);
            }
        }
    }
}
