//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication.Framework.Message {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrameworkValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkValidationMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication.Framework.Message.FrameworkValidationMessage", typeof(FrameworkValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アルファベットのみ入力が可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlphabetValueCheckMessage {
            get {
                return ResourceManager.GetString("AlphabetValueCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アルファベットと数字のみ入力が可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlphanomicsValueCheckMessage {
            get {
                return ResourceManager.GetString("AlphanomicsValueCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小数値のみ入力が可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DecimalValueCheckMessage {
            get {
                return ResourceManager.GetString("DecimalValueCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Htmlエンコードが必要です。 {0}={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlValueCheckMessage {
            get {
                return ResourceManager.GetString("HtmlValueCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数値のみ入力が可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IntegerValueCheckMessage {
            get {
                return ResourceManager.GetString("IntegerValueCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。{0}={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiresInputMessage {
            get {
                return ResourceManager.GetString("RequiresInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力文字数を{2}文字以上で入力してください。 {0}={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringLengthInput1ArgsMaxMessage {
            get {
                return ResourceManager.GetString("StringLengthInput1ArgsMaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力文字数を{2}文字以下で入力してください。 {0}={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringLengthInput1ArgsMinMessage {
            get {
                return ResourceManager.GetString("StringLengthInput1ArgsMinMessage", resourceCulture);
            }
        }
    }
}
